/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cola;

/**
 *
 * @author David
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    ClaseCola objetoCola;

    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnVacia = new javax.swing.JButton();
        btnLlenar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTamanioCola = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnElementos = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        txaResultado = new java.awt.TextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        txtCantidadCambiar = new javax.swing.JTextField();
        txtCodigoCambiar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAscendente = new javax.swing.JButton();
        btnPila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnVacia.setText("Vacia");
        btnVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciaActionPerformed(evt);
            }
        });

        btnLlenar.setText("Llenar");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio");

        jLabel5.setText("Minimo");

        jLabel6.setText("Tamaño de la cola");

        txtTamanioCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioColaActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear Cola");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnElementos.setText("Elementos");
        btnElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementosActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        txaResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txaResultado.setEditable(false);
        txaResultado.setName(""); // NOI18N

        jLabel7.setText("Creado por David Enríquez");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Colas");

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        txtCodigoCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCambiarActionPerformed(evt);
            }
        });

        jLabel9.setText("Codigo");

        jLabel10.setText("Cantidad");

        btnAscendente.setText("Examen (ascendente)");
        btnAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscendenteActionPerformed(evt);
            }
        });

        btnPila.setText("Boton pila, suple");
        btnPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVacia))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLlenar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRetirar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnElementos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReporte)
                        .addGap(37, 37, 37)
                        .addComponent(btnAscendente)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnPila)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVender)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCodigoCambiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(txtCantidadCambiar, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtTamanioCola))
                .addGap(37, 37, 37)
                .addComponent(btnCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTamanioCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigoCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidadCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVender)
                                    .addComponent(btnComprar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRetirar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLlenar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVacia))
                            .addComponent(txaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnElementos)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReporte)
                                    .addComponent(btnAscendente))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPila)
                        .addGap(191, 191, 191))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String codigo = txtCodigo.getText();
        String nombre = txtNombre.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double precio = Double.parseDouble(txtPrecio.getText());
        int minimo = Integer.parseInt(txtMinimo.getText());

        Productos producto = new Productos(codigo, nombre, cantidad, precio, minimo);
        objetoCola.Ingresar(producto);
        String r = "Elemento ingresado correctamente";
        txaResultado.setText(r);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtTamanioColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioColaActionPerformed

    }//GEN-LAST:event_txtTamanioColaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        int tamanio = Integer.parseInt(txtTamanioCola.getText());
        objetoCola = new ClaseCola(tamanio);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        Object r = objetoCola.Retirar();

        Productos s;
        if (r == null) {
            txaResultado.setText("La cola está vacía. no se puede retirar");
        } else {
            s = (Productos) r;//convirtiendo el tipo de dato usado a string
            txaResultado.setText("Elemento retirado correctamente " + s.getCodigo() + "\t" + s.getNombre() + "\t" + s.getCantidad() + "\t" + s.getPrecio() + "\t" + s.getMinimo() + "\n");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
        if (objetoCola.Llena()) {
            txaResultado.setText("La cola SI se encuentra llena");
        } else {
            txaResultado.setText("La cola NO se encuentra llena");
        }
    }//GEN-LAST:event_btnLlenarActionPerformed

    private void btnVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciaActionPerformed
        if (objetoCola.Vacia()) {
            txaResultado.setText("La cola SI se encuentra vacia");
        } else {
            txaResultado.setText("La cola NO se encuentra vacia ");
        }
    }//GEN-LAST:event_btnVaciaActionPerformed

    private void btnElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementosActionPerformed
        int r = objetoCola.getNumElementos();
        txaResultado.setText("" + r);
    }//GEN-LAST:event_btnElementosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        Object q;
        String s = "";
        Productos o;
        ClaseCola pilaAux = new ClaseCola(objetoCola.getTam());
        while (!objetoCola.Vacia()) {
            q = objetoCola.Retirar();
            pilaAux.Ingresar(q);
            o = (Productos) q;
            s = s + "" + o.getCodigo() + "\t" + o.getNombre() + "\t" + o.getCantidad() + "\t" + o.getPrecio() + "\t" + o.getMinimo() + "\n";

        }
        while (!pilaAux.Vacia()) {
            objetoCola.Ingresar(pilaAux.Retirar());
        }
        txaResultado.setText(s);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void txtCodigoCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCambiarActionPerformed

    }//GEN-LAST:event_txtCodigoCambiarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        Object q;
        String s = "";
        Productos o;
        ClaseCola pilaAux = new ClaseCola(objetoCola.getTam());

        while (!objetoCola.Vacia()) {
            int aux;
            String codVender = txtCodigoCambiar.getText();
            int numVender = Integer.parseInt(txtCantidadCambiar.getText());
            q = objetoCola.Retirar();
            pilaAux.Ingresar(q);
            o = (Productos) q;
            int auxiliar = Integer.parseInt(o.getCodigo());
            if (o.getCodigo().equals(codVender)) {
                o.setCantidad(o.getCantidad() + numVender);
            }
            s = s + "" + o.getCodigo() + "\t" + o.getNombre() + "\t" + o.getCantidad() + "\t" + o.getPrecio() + "\t" + o.getMinimo() + "\n";

        }
        while (!pilaAux.Vacia()) {
            objetoCola.Ingresar(pilaAux.Retirar());
        }
        txaResultado.setText(s);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        Object q;
        String s = "";
        Productos o;
        ClaseCola pilaAux = new ClaseCola(objetoCola.getTam());

        while (!objetoCola.Vacia()) {

            String codVender = txtCodigoCambiar.getText();
            int numVender = Integer.parseInt(txtCantidadCambiar.getText());
            q = objetoCola.Retirar();
            pilaAux.Ingresar(q);
            o = (Productos) q;

            int auxiliar = Integer.parseInt(o.getCodigo());
            if (o.getCodigo().equals(codVender)) {
                o.setCantidad(o.getCantidad() - numVender);
            }
            s = s + "" + o.getCodigo() + "\t" + o.getNombre() + "\t" + o.getCantidad() + "\t" + o.getPrecio() + "\t" + o.getMinimo() + "\n";

        }
        while (!pilaAux.Vacia()) {
            objetoCola.Ingresar(pilaAux.Retirar());
        }
        txaResultado.setText(s);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscendenteActionPerformed
        Object qCola, qPila = "";
        String s = "";
        Productos producto, auxProducto;
        ClasePila auxiliarPila = new ClasePila(objetoCola.getTam());
        ClasePila pila = new ClasePila(objetoCola.getTam());

        while (!objetoCola.Vacia()) {
            int numero, numeroPila;

            qCola = objetoCola.Retirar();

            producto = (Productos) qCola;

            // qPila= pila.Cima();
            //auxProducto=(Productos)qPila;
            
           

            if (pila.Cima() == null) {
                pila.Apilar(producto);

                while (pila.Cima() != null) {
                    pila.Apilar((Productos)auxiliarPila.Desapilar());
                }

            } else {
                qPila = pila.Cima();
                auxProducto = (Productos) qPila;
                
                numero = (int) producto.getPrecio();
                numeroPila = (int) auxProducto.getPrecio();

                if (numero <= numeroPila) {
                    pila.Apilar(producto);
                    while (pila.Cima() != null) {
                        pila.Apilar(auxiliarPila.Desapilar());
                    }
                }else{
                     auxiliarPila.Apilar(producto);
                            
                            }
            }


        }
        while (!pila.Vacia()) {
            objetoCola.Ingresar(pila.Desapilar());
        }

    }//GEN-LAST:event_btnAscendenteActionPerformed

    private void btnPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilaActionPerformed
        Object q;
        Object auxiliar;
        String s = "";
        Productos o;
        Productos productos;
        
        ClasePila pilaAux = new ClasePila(objetoCola.getTam());
        
        ClaseCola colaLlenar=new ClaseCola(objetoCola.getTam());

        while (!objetoCola.Vacia()) {

           
            q = objetoCola.Retirar();
            auxiliar=q;
            colaLlenar.Ingresar(q);
            
             o = (Productos) auxiliar;
             
             // Como dice proximo a acabar, le puse para que me reciba desde el valor minimo +1 del producto
             if(o.getCantidad()<=o.getMinimo()+1  ){
                  pilaAux.Apilar(q);
                  s = s + "" + o.getCodigo() + "\t" + o.getNombre() + "\t" + o.getCantidad() + "\t" + o.getPrecio() + "\t" + o.getMinimo() + "\n";
             }
          
        }
        while (!colaLlenar.Vacia()) {
            objetoCola.Ingresar(colaLlenar.Retirar());
        }
        txaResultado.setText(s);
        

    }//GEN-LAST:event_btnPilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAscendente;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnElementos;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLlenar;
    private javax.swing.JButton btnPila;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnVacia;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextArea txaResultado;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadCambiar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCambiar;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamanioCola;
    // End of variables declaration//GEN-END:variables
}
